export const tripActionTypes = {
    GET_ALL_TRIPS_START: 'GET_ALL_TRIPS_START',
    GET_ALL_TRIPS_SUCCESS: 'GET_ALL_TRIPS_SUCCESS',
    GET_ALL_TRIPS_FAILURE: 'GET_ALL_TRIPS_FAILURE',

    TRIP_CREATE_START: 'TRIP_CREATE_START',
    TRIP_CREATE_SUCCESS: 'TRIP_CREATE_SUCCESS',
    TRIP_CREATE_FAILURE: 'TRIP_CREATE_FAILURE',

    GET_TRIPS_BY_AGENCY_START: 'GET_TRIPS_BY_AGENCY_START',
    GET_TRIPS_BY_AGENCY_SUCCESS: 'GET_TRIPS_BY_AGENCY_SUCCESS',
    GET_TRIPS_BY_AGENCY_FAILURE: 'GET_TRIPS_BY_AGENCY_FAILURE',
}