export const tripActionTypes = {
    GET_ALL_TRIPS_START: 'GET_ALL_TRIPS_START',
    GET_ALL_TRIPS_SUCCESS: 'GET_ALL_TRIPS_SUCCESS',
    GET_ALL_TRIPS_FAILURE: 'GET_ALL_TRIPS_FAILURE',

    TRIP_CREATE_START: 'TRIP_CREATE_START',
    TRIP_CREATE_SUCCESS: 'TRIP_CREATE_SUCCESS',
    TRIP_CREATE_FAILURE: 'TRIP_CREATE_FAILURE',

    TRIP_DELETE_START: 'TRIP_DELETE_START',
    TRIP_DELETE_SUCCESS: 'TRIP_DELETE_SUCCESS',
    TRIP_DELETE_FAILURE: 'TRIP_DELETE_FAILURE',

    GET_TRIPS_BY_AGENCY_START: 'GET_TRIPS_BY_AGENCY_START',
    GET_TRIPS_BY_AGENCY_SUCCESS: 'GET_TRIPS_BY_AGENCY_SUCCESS',
    GET_TRIPS_BY_AGENCY_FAILURE: 'GET_TRIPS_BY_AGENCY_FAILURE',

    GET_TRIP_BY_ID: 'GET_TRIP_BY_ID',

    UPDATE_SEATS_START: 'UPDATE_SEATS_START',
    UPDATE_SEATS_SUCCESS: 'UPDATE_SEATS_SUCCESS',
    UPDATE_SEATS_FAILURE: 'UPDATE_SEATS_FAILURE',
}