version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    hostname: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    volumes:
      - ./client:/usr/app/client
    depends_on:
      - server
    ports:
      - "3000:3000"