export const ticketActionTypes = {
    MAKE_PAYMENT_START: 'MAKE_PAYMENT_START',
    MAKE_PAYMENT_SUCCESS: 'MAKE_PAYMENT_SUCCESS',
    MAKE_PAYMENT_FAILURE: 'MAKE_PAYMENT_FAILURE',

    SELECT_SEATS: 'SELECT_SEATS',
    ADD_CONTACT_INFO: 'ADD_CONTACT_INFO',

    CHECK_COMPLETE_TOKEN_START: 'CHECK_COMPLETE_TOKEN_START',
    CHECK_COMPLETE_TOKEN_SUCCESS: 'CHECK_COMPLETE_TOKEN_SUCCESS',
    CHECK_COMPLETE_TOKEN_FAILURE: 'CHECK_COMPLETE_TOKEN_FAILURE',

    FIND_TICKET_START: 'FIND_TICKET_START',
    FIND_TICKET_SUCCESS: 'FIND_TICKET_SUCCESS',
    FIND_TICKET_FAILURE: 'FIND_TICKET_FAILURE',
}