export const vipSeatsList = {
    type: 'vip',
    seats: [
        { number: '1A', isValid: true },
        { number: '2A', isValid: true },
        { number: '3A', isValid: true },
        { number: '4A', isValid: true },
        { number: '5A', isValid: true },
        { number: '6A', isValid: true },
        { number: '7A', isValid: true },
        { number: '8A', isValid: true },
        { number: '9A', isValid: true },
        { number: '10A', isValid: true },
        { number: '1B', isValid: true },
        { number: '2B', isValid: true },
        { number: '3B', isValid: true },
        { number: '4B', isValid: true },
        { number: '5B', isValid: true },
        { number: '6B', isValid: true },
        { number: '7B', isValid: true },
        { number: '8B', isValid: true },
        { number: '9B', isValid: true },
        { number: '10B', isValid: true },
        { number: '10C', isValid: true },
        { number: '1D', isValid: true },
        { number: '2D', isValid: true },
        { number: '3D', isValid: true },
        { number: '4D', isValid: true },
        { number: '5D', isValid: true },
        { number: '6D', isValid: true },
        { number: '7D', isValid: true },
        { number: '8D', isValid: true },
        { number: '9D', isValid: true },
        { number: '10D', isValid: true },
    ]
};


export const normalSeatsList = {
    type: 'normal',
    seats: [
        { number: '1A', isValid: true },
        { number: '2A', isValid: true },
        { number: '3A', isValid: true },
        { number: '4A', isValid: true },
        { number: '5A', isValid: true },
        { number: '6A', isValid: true },
        { number: '7A', isValid: true },
        { number: '8A', isValid: true },
        { number: '9A', isValid: true },
        { number: '10A', isValid: true },
        { number: '1B', isValid: true },
        { number: '2B', isValid: true },
        { number: '3B', isValid: true },
        { number: '4B', isValid: true },
        { number: '5B', isValid: true },
        { number: '6B', isValid: true },
        { number: '7B', isValid: true },
        { number: '8B', isValid: true },
        { number: '9B', isValid: true },
        { number: '10B', isValid: true },
        { number: '1C', isValid: true },
        { number: '2C', isValid: true },
        { number: '3C', isValid: true },
        { number: '4C', isValid: true },
        { number: '5C', isValid: true },
        { number: '6C', isValid: true },
        { number: '7C', isValid: true },
        { number: '8C', isValid: true },
        { number: '9C', isValid: true },
        { number: '10C', isValid: true },
        { number: '1D', isValid: true },
        { number: '2D', isValid: true },
        { number: '3D', isValid: true },
        { number: '4D', isValid: true },
        { number: '5D', isValid: true },
        { number: '6D', isValid: true },
        { number: '7D', isValid: true },
        { number: '8D', isValid: true },
        { number: '9D', isValid: true },
        { number: '10D', isValid: true }
    ]
};