export const exchangeActionTypes = {
    GET_EXCHANGE_RATE_START: 'GET_EXCHANGE_RATE_START',
    GET_EXCHANGE_RATE_SUCCESS: 'GET_EXCHANGE_RATE_SUCCESS',
    GET_EXCHANGE_RATE_FAILURE: 'GET_EXCHANGE_RATE_FAILURE',

    CREATE_EXCHANGE_RATE_START: 'CREATE_EXCHANGE_RATE_START',
    CREATE_EXCHANGE_RATE_SUCCESS: 'CREATE_EXCHANGE_RATE_SUCCESS',
    CREATE_EXCHANGE_RATE_FAILURE: 'CREATE_EXCHANGE_RATE_FAILURE',

    UPDATE_EXCHANGE_RATE_START: 'UPDATE_EXCHANGE_RATE_START',
    UPDATE_EXCHANGE_RATE_SUCCESS: 'UPDATE_EXCHANGE_RATE_SUCCESS',
    UPDATE_EXCHANGE_RATE_FAILURE: 'UPDATE_EXCHANGE_RATE_FAILURE',
}