export const adminActionTypes = {
    GET_ALL_USER_START: 'GET_ALL_USER_START',
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAILURE: 'GET_ALL_USER_FAILURE',

    UPDATE_USER_ROLE_START: 'UPDATE_USER_ROLE_START',
    UPDATE_USER_ROLE_SUCCESS: 'UPDATE_USER_ROLE_SUCCESS',
    UPDATE_USER_ROLE_FAILURE: 'UPDATE_USER_ROLE_FAILURE',

    DELETE_USER_START: 'DELETE_USER_START',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',

    GET_ALL_CITIES_START: 'GET_ALL_CITIES_START',
    GET_ALL_CITIES_SUCCESS: 'GET_ALL_CITIES_SUCCESS',
    GET_ALL_CITIES_FAILURE: 'GET_ALL_CITIES_FAILURE',

    ADD_CITY_START: 'ADD_CITY_START',
    ADD_CITY_SUCCESS: 'ADD_CITY_SUCCESS',
    ADD_CITY_FAILURE: 'ADD_CITY_FAILURE',

    DELETE_CITY_START: 'DELETE_CITY_START',
    DELETE_CITY_SUCCESS: 'DELETE_CITY_SUCCESS',
    DELETE_CITY_FAILURE: 'DELETE_CITY_FAILURE'
}