export const cityActionTypes = {
    GET_ALL_CITIES_START: 'GET_ALL_CITIES_START',
    GET_ALL_CITIES_SUCCESS: 'GET_ALL_CITIES_SUCCESS',
    GET_ALL_CITIES_FAILURE: 'GET_ALL_CITIES_FAILURE',

    ADD_CITY_START: 'ADD_CITY_START',
    ADD_CITY_SUCCESS: 'ADD_CITY_SUCCESS',
    ADD_CITY_FAILURE: 'ADD_CITY_FAILURE',

    DELETE_CITY_START: 'DELETE_CITY_START',
    DELETE_CITY_SUCCESS: 'DELETE_CITY_SUCCESS',
    DELETE_CITY_FAILURE: 'DELETE_CITY_FAILURE'
}