export const userActionTypes = {
    USER_LOGIN_START: 'USER_LOGIN_START',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    USER_REGISTER_START: 'USER_REGISTER_START',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    ACCOUNT_ACTIVATION_START: 'ACCOUNT_ACTIVATION_START',
    ACCOUNT_ACTIVATION_SUCCESS: 'ACCOUNT_ACTIVATION_SUCCESS',
    ACCOUNT_ACTIVATION_FAILURE: 'ACCOUNT_ACTIVATION_FAILURE',

    CHECK_TOKEN_STATUS_START: 'CHECK_TOKEN_STATUS_START',
    CHECK_TOKEN_STATUS_SUCCESS: 'CHECK_TOKEN_STATUS_SUCCESS',
    CHECK_TOKEN_STATUS_FAILURE: 'CHECK_TOKEN_STATUS_FAILURE',

    USER_LOGOUT_ACTION: 'USER_LOGOUT_ACTION',

    CHECK_AUTH: 'CHECK_AUTH',
    ERROR_RESET: 'ERROR_RESET'
}