export const userActionTypes = {
    USER_LOGIN_START: 'USER_LOGIN_START',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    USER_REGISTER_START: 'USER_REGISTER_START',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    USER_LOGOUT_ACTION: 'USER_LOGOUT_ACTION',

    CHECK_AUTH: 'CHECK_AUTH',
    ERROR_RESET: 'ERROR_RESET'
}