export const agencyActionTypes = {
    CREATE_EXPRESS_AGENCY_START: 'CREATE_EXPRESS_AGENCY_START',
    CREATE_EXPRESS_AGENCY_SUCCESS: 'CREATE_EXPRESS_AGENCY_SUCCESS',
    CREATE_EXPRESS_AGENCY_FAILURE: 'CREATE_EXPRESS_AGENCY_FAILURE',

    GET_OWN_EXPRESS_AGENCY_START: 'GET_OWN_EXPRESS_AGENCY_START',
    GET_OWN_EXPRESS_AGENCY_SUCCESS: 'GET_OWN_EXPRESS_AGENCY_SUCCESS',
    GET_OWN_EXPRESS_AGENCY_FAILURE: 'GET_OWN_EXPRESS_AGENCY_FAILURE',

    GET_ALL_EXPRESS_AGENCY_START: 'GET_ALL_EXPRESS_AGENCY_START',
    GET_ALL_EXPRESS_AGENCY_SUCCESS: 'GET_ALL_EXPRESS_AGENCY_SUCCESS',
    GET_ALL_EXPRESS_AGENCY_FAILURE: 'GET_ALL_EXPRESS_AGENCY_FAILURE'
}