export const agencyActionTypes = {
    CREATE_EXPRESS_AGENCY_START: 'CREATE_EXPRESS_AGENCY_START',
    CREATE_EXPRESS_AGENCY_SUCCESS: 'CREATE_EXPRESS_AGENCY_SUCCESS',
    CREATE_EXPRESS_AGENCY_FAILURE: 'CREATE_EXPRESS_AGENCY_FAILURE',

    GET_OWN_EXPRESS_AGENCY_START: 'GET_OWN_EXPRESS_AGENCY_START',
    GET_OWN_EXPRESS_AGENCY_SUCCESS: 'GET_OWN_EXPRESS_AGENCY_SUCCESS',
    GET_OWN_EXPRESS_AGENCY_FAILURE: 'GET_OWN_EXPRESS_AGENCY_FAILURE',

    GET_ALL_EXPRESS_AGENCY_START: 'GET_ALL_EXPRESS_AGENCY_START',
    GET_ALL_EXPRESS_AGENCY_SUCCESS: 'GET_ALL_EXPRESS_AGENCY_SUCCESS',
    GET_ALL_EXPRESS_AGENCY_FAILURE: 'GET_ALL_EXPRESS_AGENCY_FAILURE',

    CHECK_SOLD_TICKETS_START: 'CHECK_SOLD_TICKETS_START',
    CHECK_SOLD_TICKETS_SUCCESS: 'CHECK_SOLD_TICKETS_SUCCESS',
    CHECK_SOLD_TICKETS_FAILURE: 'CHECK_SOLD_TICKETS_FAILURE',

    RESET_SOLD_TICKETS_IN_AGENCY_PANEL: 'RESET_SOLD_TICKETS_IN_AGENCY_PANEL'
}